apiVersion: v1
# 이 파일에서 정의하는 kubernetes 의 리소스 유형을 지정한다.
# kind 의 속성에 따라 spec 아래의 스키마가 변한다 e.g) ReplicaSet, Deployment, ...
kind: Pod
metadata:
  name: simple-echo
  # 리소스를 정의하기 위한 속성으로 Pod 의 경우, Pod 을 구성하는 컨테이너를 정의한다.
spec:
  containers:
    - name: nginx
      image: gihyodocker/nginx:latest
      env:
        - name: BACKEND_HOST # 요청의 proxy 대상이 될 값
          value: localhost:8080
      ports:
        - containerPort: 80
    - name: echo
      image: gihyodocker/echo:latest
      ports:
        - containerPort: 8080